[package]
name = "bevy_tutorial"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 3

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = {version = "0.7.0", features = ["dynamic"]}
rand = "0.7.3"
queues = "1.0.2"